alias lt='ls --human-readable --size -1 -S --classify'
alias ll='ls --color=auto -alF'
alias la='ls --color=auto -alF'
alias l='ls --color=auto -CF'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias df='df -H'
alias du='du -ch'
alias cpv='rsync -ah --info=progress2'
alias tailf='tail -f'
